### ISSUE TITLE
Already filled vars but it said Variables for the first app are not fully filled.

### ISSUE THREAD

**Issue by alok99-git** [tiararosebiezetta/HerokuDynoSwitcher#15]
I already fill FIRST_PROCESSTYPE, FIRST_A_APPNAME, FIRST_A_APIKEY, FIRST_B_APPNAME, FIRST_B_APIKEY but it said Variables for the first app are not fully filled (Check telegraph link for more detail)

https://telegra.ph/file/7e87d45e9f6302cd9b95b.jpg
https://telegra.ph/file/77ce0982d031b2fbca587.jpg

**Comment by tiararosebiezetta** [comment]
Sorry wrong string, check # 1. I'll make a fix string commit.

**Comment by tiararosebiezetta** [comment]
Fix done.
