### ISSUE TITLE
please add commercial use

### ISSUE THREAD

**Issue by ghost** [tiararosebiezetta/HerokuDynoSwitcher#9]
i cant use it for helping my friends add code so user can input

**Comment by tiararosebiezetta** [comment]
I don't really understand what you mean. If you want to apply this repo, fork and see the github actions tutorial. 

Or do you want a frontend for users to input the vars? If yes, then I need to write some flask codes and some databases, while I'm not proficient in those two. I'll really appreciate it if someone can PR that hehe. But for now, if you want a frontend, I can't as I have a little knowledge about flask and databases (Postgresql, MongoDB, etc)

**Comment by tiararosebiezetta** [comment]
No further information, closed.

**Comment by ghost** [comment]
ok i wanted frontend only

**Comment by ghost** [comment]
that is what i meant but since you cant do that i will adjust
